# Generated by Django 5.1.4 on 2025-09-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_alter_buslocation_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerprofile',
            name='addr1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='passengerprofile',
            name='addr2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='passengerprofile',
            name='area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='passengerprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='passengerprofile',
            name='postcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='passengerprofile',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='passengerprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
